--------------------------CÉSAR SILVA-----------------------------------
--------------------------JULIO RUIZ------------------------------------
------------------------TABLA EQUIPOS-----------------------------------
CREATE TABLE EQUIPO
(
CODIGO INT NOT NULL,
AFORO INT NOT NULL,
CIUDAD VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
ESTADIO VARCHAR(50) NOT NULL,
FECHA_FUNDACION DATE NOT NULL,
LADO VARCHAR(10) NOT NULL

CONSTRAINT PK_CODIGO PRIMARY KEY(CODIGO),
CONSTRAINT CHK_FECHA_FUNDACION CHECK(FECHA_FUNDACION > '1-1-1950'),
CONSTRAINT CHK_LADO CHECK(LADO = 'LOCAL' OR LADO = 'VISITANTE')
)

INSERT EQUIPO
(CODIGO, AFORO, CIUDAD, NOMBRE, ESTADIO, FECHA_FUNDACION, LADO)
VALUES
(1, 300000, 'PARIS', 'PSG', 'PARQUE DE LOS PRINCIPES', '1970-8-12', 'LOCAL')
INSERT EQUIPO
(CODIGO, AFORO, CIUDAD, NOMBRE, ESTADIO, FECHA_FUNDACION, LADO)
VALUES
(2, 250000, 'BARCELONA', 'FC BARCELONA', 'CAMP NOU', '1950-2-14', 'VISITANTE')
-------------------------TABLA PARTIDO----------------------------------
CREATE TABLE PARTIDO
(
CODIGO INT NOT NULL,
JORNADA INT NOT NULL,
FECHA DATE NOT NULL,
HORA_INICIO TIME NOT NULL,
GOL_LOCAL INT NOT NULL,
GOL_VISITA INT NOT NULL,
MARCADOR VARCHAR(10) NOT NULL,
CELOCAL INT NOT NULL,
CEVISITA INT NOT NULL

CONSTRAINT PK_CODIGO1 PRIMARY KEY(CODIGO),
CONSTRAINT CHK_FECHA CHECK(MONTH(FECHA) < 07 OR MONTH(FECHA) > 10),
CONSTRAINT CHK_EQUIPOS CHECK(CELOCAL != CEVISITA),
CONSTRAINT CHK_MARCADOR CHECK(MARCADOR = 'GANA LOCAL' OR MARCADOR = 'GANA VISITA' OR MARCADOR = 'EMPATE'),
CONSTRAINT CHK_HORA_INICIO CHECK(HORA_INICIO > '12:00:00' AND HORA_INICIO < '22:00:00')
)

INSERT PARTIDO
(CODIGO, JORNADA, FECHA, HORA_INICIO, GOL_LOCAL, GOL_VISITA, MARCADOR, CELOCAL, CEVISITA)
VALUES
(1, 1, GETDATE(), '12:01:00', 1, 1, 'EMPATE', 1, 2)
INSERT PARTIDO
(CODIGO, JORNADA, FECHA, HORA_INICIO, GOL_LOCAL, GOL_VISITA, MARCADOR, CELOCAL, CEVISITA)
VALUES
(2, 2, GETDATE(), '20:01:00', 5, 1, 'GANA LOCAL', 1, 2)
INSERT PARTIDO
(CODIGO, JORNADA, FECHA, HORA_INICIO, GOL_LOCAL, GOL_VISITA, MARCADOR, CELOCAL, CEVISITA)
VALUES
(3, 2, '2022-1-12', '12:01:00', 0, 0, 'EMPATE', 2, 1)
DROP TABLE PARTIDO
---------------------------TABLA JUGADOR--------------------------------
CREATE TABLE JUGADOR
(
CODIGO INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
FECHA_NAC DATE NOT NULL,
POSICION VARCHAR(20),
EQUIPOST INT NOT NULL,
JORNADA INT NOT NULL,
GOLES INT NOT NULL,
CODIGOEACT INT NOT NULL,
CAMBIO_EQUIPO VARCHAR(2) NOT NULL

CONSTRAINT PK_CODIGO2 PRIMARY KEY(CODIGO),
CONSTRAINT CHK_FECHA_NAC CHECK((YEAR(GETDATE())-YEAR(FECHA_NAC)) > 15),
CONSTRAINT FK_EQUIPO_ACTUAL FOREIGN KEY(CODIGOEACT) REFERENCES EQUIPO(CODIGO),
CONSTRAINT CHK_CAMBIO CHECK(CAMBIO_EQUIPO = 'SI' OR CAMBIO_EQUIPO = 'NO'),
CONSTRAINT CHK_POSICION CHECK(POSICION = 'DELANTERO' OR POSICION = 'MEDIOCAMPISTA' OR POSICION = 'DEFENSA' OR POSICION = 'PORTERO')
)

INSERT JUGADOR
(CODIGO, NOMBRE, FECHA_NAC, POSICION, EQUIPOST, JORNADA, GOLES, CODIGOEACT, CAMBIO_EQUIPO)
VALUES
(1, 'LIONEL MESSI', '1987-5-24', 'DELANTERO', 2, 1, 10, 2, 'SI')
INSERT JUGADOR
(CODIGO, NOMBRE, FECHA_NAC, POSICION, EQUIPOST, JORNADA, GOLES, CODIGOEACT, CAMBIO_EQUIPO)
VALUES
(2, 'CRISTIANO RONALDO', '1985-2-5', 'MEDIOCAMPISTA', 5, 2, 5, 1, 'NO')
