

CREATE TABLE ALMACEN 
(
	--IDENTITY[(SEED,INCREMENT)] PRIMERA FILA QUE SE CARGO TENDRA VALOR DE 10 CON SU VALOR INCREMENTAL DE 10
	ID_ALMACEN INT IDENTITY(10,10) NOT NULL ,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50),
	FECHA_APERTURA DATE,
	HORARIO VARCHAR(5) NOT NULL,
	ID_LOCALIDAD INT,
	REGISTRO_FECHA_HORA DATETIME DEFAULT GETDATE()

	CONSTRAINT PK_ALMACEN PRIMARY KEY (ID_ALMACEN),
	CONSTRAINT FK_LOCALIDAD_ALMACEN FOREIGN KEY(ID_LOCALIDAD) REFERENCES LOCALIDAD(ID_LOCALIDAD),
	--El LIKEoperador se usa en una WHEREcláusula para buscar un patrón específico en una columna.
	CONSTRAINT CHK_HOR CHECK (HORARIO LIKE '[MAT][0-9]' OR HORARIO LIKE '[VESP][0-9]'),--expresiones regulares con check
) 
INSERT ALMACEN
(FECHA_APERTURA,NOMBRE,HORARIO)
VALUES
('01/05/2022','PEDRO','VESP5')

SELECT * FROM ALMACEN
DROP TABLE ALMACEN
------------------------------------------------------------------------------


CREATE TABLE INVENTARIO
(
	ID_ARTICULO INT IDENTITY(10,10)NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CANTI_INVENTARIO INT,
	PRECIO_UNI DECIMAL(6,2),
	ID_ALMACEN INT,
	REGISTRO_FECHA_HORA DATETIME DEFAULT GETDATE()

	CONSTRAINT PK_ARTICULOS PRIMARY KEY (ID_ARTICULO),
	CONSTRAINT CHK_PRECIOUNI CHECK (PRECIO_UNI > 0)
)
INSERT INVENTARIO
(NOMBRE,CANTI_INVENTARIO,PRECIO_UNI,ID_ALMACEN)
VALUES
('PEDRO',4,1,'23')

SELECT * FROM INVENTARIO
DROP TABLE INVENTARIO

-------------------------------------------------------------------------------

CREATE TABLE EMPLEADO
(
	ID_EMPLEADO INT IDENTITY(10,10) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50),
	GENERO VARCHAR(15),
	NIT VARCHAR(10),
	REGISTRO_FECHA_HORA DATETIME DEFAULT GETDATE()

	CONSTRAINT PK_EMPELADO PRIMARY KEY (ID_EMPLEADO),
	CONSTRAINT UC_MISMO_NIT UNIQUE(NIT),--unique checK

)
DROP TABLE EMPLEADO

--------------------------------------------------------------------------------


CREATE TABLE LOCALIDAD
(
	ID_LOCALIDAD INT IDENTITY(10,10) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	REGISTRO_FECHA_HORA DATETIME DEFAULT GETDATE()

	CONSTRAINT PK_LOCALIDAD PRIMARY KEY (ID_LOCALIDAD)

)
DROP TABLE LOCALIDAD

--------------------------------------------------------------------------------

CREATE TABLE ALMACENEMPLEADO(
	ID_ALMACEN_EMPLEADO INT IDENTITY(10,10),
	ID_ALMACEN INT NOT NULL,
	ID_EMPLEADO INT,
	FUNCION_EMPLEADO VARCHAR(50),
	REGISTRO_FECHA_HORA DATETIME DEFAULT GETDATE()

	CONSTRAINT PK_ALMACEN_EMPLEADO PRIMARY KEY(ID_ALMACEN_EMPLEADO),
	CONSTRAINT UC_ALMACEN UNIQUE (ID_ALMACEN,ID_EMPLEADO,FUNCION_EMPLEADO),
	CONSTRAINT FK_ALMACEN_EMPLEADO_ALMACEN FOREIGN KEY(ID_ALMACEN) REFERENCES ALMACEN(ID_ALMACEN),
	CONSTRAINT FK_ALMACEN_EMPLEADO_EMPLEADO FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
	CONSTRAINT CHK_FUNCIONESS CHECK (FUNCION_EMPLEADO = 'SEGURIDAD'OR FUNCION_EMPLEADO = 'GERENTE'OR FUNCION_EMPLEADO = 'CAJERO'),
	CONSTRAINT UC_FUNCION_EMPL UNIQUE(FUNCION_EMPLEADO)
)
DROP TABLE ALMACENEMPLEADO
