
--DDL
-----------------------------------------------------------------
---RESTRICCION VALORES NULOS
DROP TABLE PELICULA 
CREATE TABLE PELICULA
(
	ID_PELICULA INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_LANZAMIENTO DATE
	CONSTRAINT UC_PELICULA_NOMBRE UNIQUE(NOMBRE)
	--CONSTRAINT NOMBRE_CONSTRAINT TIPO DE RESTRICCION (SOBREQUE)
)

-----------------------------------------------------------------
---RESTRICCION UNICA 
DROP TABLE PELICULA 
CREATE TABLE PELICULA
(
	ID_PELICULA INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_LANZAMIENTO DATE
	CONSTRAINT UC_PELICULA_NOMBRE UNIQUE(NOMBRE)
	--CONSTRAINT NOMBRE_CONSTRAINT TIPO DE RESTRICCION (SOBREQUE)
)
INSERT PELICULA
(ID_PELICULA ,NOMBRE,FECHA_LANZAMIENTO)
VALUES
(10,'PATITO',NULL)

INSERT PELICULA
(NOMBRE)
VALUES
('PATITO')

SELECT * FROM PELICULA















------------------------------------------------------------------
--RESTRICCION DE LLAVE PRIMARIA (NOT NULL Y UNICA)
DROP TABLE PELICULA 
CREATE TABLE PELICULA
(
	ID_PELICULA INT, 
	NOMBRE VARCHAR(100),
	FECHA_LANZAMIENTO DATE
	CONSTRAINT PK_PELICULA PRIMARY KEY (ID_PELICULA,NOMBRE)
	--hace la comparacion entre id_pelicula y nombre que no
	--puede ser duplicada
)
INSERT PELICULA
(ID_PELICULA ,NOMBRE,FECHA_LANZAMIENTO)
VALUES
(18,'PATITO2',NULL)
SELECT * FROM PELICULA






---OPCION B DEL DE ARRIBA
--COMPRUEBA LO DE LA LLAVE UNICA
DROP TABLE PELICULA 
CREATE TABLE PELICULA
(
	ID_PELICULA INT, 
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_LANZAMIENTO DATE
	CONSTRAINT PK_PELICULA PRIMARY KEY (ID_PELICULA),
	CONSTRAINT UC_PELICULA_NOMBRE UNIQUE(NOMBRE)
)
INSERT PELICULA
(ID_PELICULA ,NOMBRE,FECHA_LANZAMIENTO)
VALUES
(90,'PATITO',NULL)
SELECT * FROM PELICULA



-----------------------------------------------------------------

---VALIDACION DE DATOS
DROP TABLE PELICULA 
CREATE TABLE PELICULA
(
	ID_PELICULA INT, 
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_LANZAMIENTO DATE
	CONSTRAINT PK_PELICULA PRIMARY KEY (ID_PELICULA),
	CONSTRAINT UC_PELICULA_NOMBRE UNIQUE(NOMBRE),
	CONSTRAINT CHK_FECHA CHECK (FECHA_LANZAMIENTO >= '01/01/2022')

)
INSERT PELICULA
(ID_PELICULA ,NOMBRE,FECHA_LANZAMIENTO)
VALUES
(33,'MARIPOSA','01/05/2029')

SELECT * FROM PELICULA

------------------------------------------------------------------

--RESTRICCION DEFAULT 
DROP TABLE PELICULA 
CREATE TABLE PELICULA
(
	ID_PELICULA INT, 
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_LANZAMIENTO DATE,
	FECHA_INGRESO DATETIME DEFAULT GETDATE()--SI NO SE COLOCA FECHA DE INGRESO SE SETEA QUE POR DEFAULT NO VENGA ESE VALOR SE COLOCA LA FECHA DE HOY
	CONSTRAINT PK_PELICULA PRIMARY KEY (ID_PELICULA),
	CONSTRAINT UC_PELICULA_NOMBRE UNIQUE(NOMBRE),
	CONSTRAINT CHK_FECHA CHECK (FECHA_LANZAMIENTO >= '01/01/2022')	 

)
INSERT PELICULA
(ID_PELICULA ,NOMBRE,FECHA_LANZAMIENTO)
VALUES
(3,'PATITO4','01/05/2022')

SELECT * FROM PELICULA












-----------------------------------------------------------------
--LLAVE FORANEA
CREATE TABLE DIRECTOR_PELI
(
	ID_DIRECTOR INT PRIMARY KEY,
	NOMBRE VARCHAR(50)
)

DROP TABLE PELICULA

CREATE TABLE PELICULA
(
	ID_PELICULA INT, 
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_LANZAMIENTO DATE,
	FECHA_INGRESO DATETIME DEFAULT GETDATE(),
	ID_DIRECTOR INT
	CONSTRAINT PK_PELICULA PRIMARY KEY (ID_PELICULA),
	CONSTRAINT UC_PELICULA_NOMBRE UNIQUE(NOMBRE),
	CONSTRAINT CHK_FECHA CHECK (FECHA_LANZAMIENTO >= '01/01/2022'),	
	CONSTRAINT FK_PELICULA_DIRECTOR FOREIGN KEY(ID_DIRECTOR) REFERENCES DIRECTOR_PELI(ID_DIRECTOR)

)
------------------------
INSERT PELICULA
(ID_PELICULA ,NOMBRE,FECHA_LANZAMIENTO)
VALUES
(98,'PATIT8','01/05/2022')

------------------------
INSERT PELICULA
(ID_PELICULA ,NOMBRE,FECHA_LANZAMIENTO,ID_DIRECTOR)
VALUES
(87,'FLOR','01/05/2022',5)

SELECT * FROM PELICULA

SELECT * FROM DIRECTOR_PELI

INSERT DIRECTOR_PELI
(ID_DIRECTOR,NOMBRE)
VALUES
(5,'FERNANDO')