--Rafael Andrés Alvarez Mazariegos- 1018419
--David André Rodríguez Cano -1164619
--César Adrian Silva Pérez - 1184519
--Eddie Alejandro Girón Carranza - 1307419
--Julio Anthony Engels Ruiz Coto - 1284719

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT NOT NULL,
	NOMBRES VARCHAR(50),
	APELLIDOS VARCHAR(50),
	EDAD INT NOT NULL, --(PREGUNTA 4) TODOS SON MAYORES DE 30 
	CORRE_ELECTR VARCHAR(50),
	PAIS_ORIGEN VARCHAR(50), --EL TOTAL DEPENDIENDO EL TIPO DE CUENTA RESPECTO A CADA PAIS (PREGUNTA 2)
	DOC_IDENTIFIACION VARCHAR(50) NOT NULL,
	ID_CUENTA INT,
	TELEFONOS INT,
	TIPO_CUENTA VARCHAR(10),
	BENEFICIARIO VARCHAR(50), --(PREGUNTA 4) QUE ESTE CAMPO NO ESTE VACIO -> POR QUE AL ESTAR VACIO NO COMPARTE LA CUENTA CON NINGUNA PERSONA/CLIENTE 
	FECHA_APERTU DATETIME, -- (PREGUNTA 5) EL TOTAL DE TODAS LAS CUENTAS COMERCIALES CREADAS EN 2017 PARA ATRAS
	TIPO_MONEDA VARCHAR(50)

	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT CHK_EDAD CHECK (EDAD >= 45),
	CONSTRAINT UC_CORRE_ELECTR UNIQUE(CORRE_ELECTR),
	CONSTRAINT UC_ID_CUENTA UNIQUE(ID_CUENTA),
	CONSTRAINT CHK_TIPO_CUENTAC CHECK (TIPO_CUENTA = 'COMERCIAL' OR TIPO_CUENTA = 'PREMIUM'),
	CONSTRAINT FK_SUCURSAL_CLIENTE FOREIGN KEY (ID_CUENTA) REFERENCES SUCURSAL(ID_CUENTA),
	---CONSTRAINT FK_SUCURSAL_CLIENTE2 FOREIGN KEY (FECHA_APERTU) REFERENCES SUCURSAL(FECHA_APERTU),
	---CONSTRAINT FK_SUCURSAL_CLIENTE3 FOREIGN KEY (TIPO_CUENTA) REFERENCES SUCURSAL(TIPO_CUENTA),
	---CONSTRAINT FK_SUCURSAL_CLIENTE4 FOREIGN KEY (TIPO_MONEDA) REFERENCES SUCURSAL(TIPO_MONEDA)
)
SELECT * FROM CLIENTE
WHERE CORRE_ELECTR LIKE '%@gmail.com'---CUENTAS VALIDAS SON UNICAMENTE LAS TERMINADAS EN '@gmail.com'

INSERT CLIENTE
(ID_CLIENTE,NOMBRES,APELLIDOS,EDAD,CORRE_ELECTR,PAIS_ORIGEN,DOC_IDENTIFIACION,ID_CUENTA,TELEFONOS,TIPO_CUENTA,BENEFICIARIO,FECHA_APERTU,TIPO_MONEDA)
VALUES
(1,'CESAR RAMIRO','PINTO MONTENEGRO',50,'CHECHAPINTO@gmail.COM','hungria','325581281-K',1,'24516987','COMERCIAL','PELOPONDIO',GETDATE(),'EUROS')
INSERT CLIENTE
(ID_CLIENTE,NOMBRES,APELLIDOS,EDAD,CORRE_ELECTR,PAIS_ORIGEN,DOC_IDENTIFIACION,ID_CUENTA,TELEFONOS,TIPO_CUENTA,BENEFICIARIO,FECHA_APERTU,TIPO_MONEDA)
VALUES
(2,'JULIO ANTONIO','CASTRO',45,'JAC@gmail.com','MEXICO','325581281-H',2,'15326548','PREMIUM',NULL,GETDATE(),'DOLAR')

DROP TABLE CLIENTE

-----------------------------------------------------------------------------------------------------------------

CREATE TABLE SUCURSAL
(
    ID_CUENTA INT,
    DOC_IDENTIFIACION VARCHAR(50)NOT NULL,
    TIPO_CUENTA VARCHAR(10) NOT NULL,
	FECHA_APERTU DATETIME,
	CUENTA_NUEVA VARCHAR(2) NOT NULL, --(PREGUNTA 1) EL TOTAL DE LAS CUENTAS QUE TENGAN EN ESTE CAMPO (SI) ES EL TOTAL DE CUENTAS APERTURADAS POR DIA COMPARADAS CON LA FECHA DE APERTURA
	TIPO_MONEDA VARCHAR(50) NOT NULL,
	APERTURA_K INT

	CONSTRAINT PK_ID_CUENTA PRIMARY KEY (ID_CUENTA),
	CONSTRAINT CHK_TIPO_MONEDA CHECK (TIPO_MONEDA = 'DOLAR' OR TIPO_MONEDA = 'EURO'),
	CONSTRAINT CHK_CUENTA_NUEVA CHECK (CUENTA_NUEVA = 'SI' OR CUENTA_NUEVA = 'NO'),
	CONSTRAINT CHK_TIPO_CUENTA CHECK (TIPO_CUENTA = 'COMERCIAL' OR TIPO_CUENTA = 'PREMIUM'),
	CONSTRAINT CHK_APERTURA_K CHECK (APERTURA_K >= 50 OR APERTURA_K >= 500 OR APERTURA_K = NULL)
	---CONSTRAINT CHK_APERTURA CHECK (CUENTA_NUEVA = 'SI' AND TIPO_CUENTA = 'COMERCIAL' AND APERTURA_K >= 50),
	---CONSTRAINT CHK_APERTURA1 CHECK (CUENTA_NUEVA = 'SI' AND TIPO_CUENTA = 'PREMIUM' AND APERTURA_K >= 500),
	---CONSTRAINT CHK_APERTURA2 CHECK (CUENTA_NUEVA = 'NO' AND TIPO_CUENTA = 'PREMIUM' AND APERTURA_K = NULL),
	---CONSTRAINT CHK_APERTURA3 CHECK (CUENTA_NUEVA = 'NO' AND TIPO_CUENTA = 'COMERCIAL' AND APERTURA_K = NULL),
	---CONSTRAINT FK_CLIENTE_SUCURSAL FOREIGN KEY (DOC_IDENTIFIACION) REFERENCES CLIENTE(DOC_IDENTIFIACION)
)
SELECT* FROM SUCURSAL 

INSERT SUCURSAL
(ID_CUENTA,DOC_IDENTIFIACION,TIPO_CUENTA,FECHA_APERTU,CUENTA_NUEVA,TIPO_MONEDA,APERTURA_K)
VALUES
(1,'325581281-K','COMERCIAL',GETDATE(),'SI','EURO',50)
INSERT SUCURSAL
(ID_CUENTA,DOC_IDENTIFIACION,TIPO_CUENTA,FECHA_APERTU,CUENTA_NUEVA,TIPO_MONEDA,APERTURA_K)
VALUES
(2,'325581281-H','PREMIUM',GETDATE(),'SI','DOLAR',500)

DROP TABLE SUCURSAL

-----------------------------------------------------------------------------------------------------------------

CREATE TABLE CUENTA
(
    ID_CUENTA INT NOT NULL,
    TIPO_TRANSACCION CHAR NOT NULL,
    CONTRASEÑA VARCHAR(50) NOT NULL,
    --BALANCE DECIMAL(6,2) NOT NULL,
    USUARIO VARCHAR(50) NOT NULL,
    FECHA_HORA DATETIME DEFAULT GETDATE(),
	PAIS_ORIGEN VARCHAR(50),
	TIPO_MONEDA VARCHAR(50),
	TIPO_CUENTA VARCHAR(50)
	
	CONSTRAINT PK_ID_CUENTA1 PRIMARY KEY (ID_CUENTA),
	CONSTRAINT CHK_TIPO_MONEDAM CHECK (TIPO_MONEDA = 'DOLAR' OR TIPO_MONEDA = 'EURO'),
	CONSTRAINT CHK_TIPO_TRANSACCION CHECK (TIPO_TRANSACCION  = 'A' OR TIPO_TRANSACCION  = 'B'),
	CONSTRAINT UC_CONTRASEÑA UNIQUE(CONTRASEÑA),
	CONSTRAINT UC_USUARIO UNIQUE(USUARIO),
	CONSTRAINT CHK_TIPO_CUENTAM CHECK (TIPO_CUENTA = 'COMERCIAL' OR TIPO_CUENTA = 'PREMIUM'),
	CONSTRAINT CHK_TRANSACCION_A CHECK (TIPO_CUENTA = 'COMERCIAL' AND TIPO_TRANSACCION = 'A' OR TIPO_CUENTA = 'PREMIUM' AND TIPO_TRANSACCION = 'B' OR TIPO_TRANSACCION = 'A'),
	CONSTRAINT FK_CLIENTE_CUENTA FOREIGN KEY (ID_CUENTA) REFERENCES CLIENTE(ID_CUENTA),
	---CONSTRAINT FK_CLIENTE_CUENTA2 FOREIGN KEY (TIPO_MONEDA) REFERENCES CLIENTE(TIPO_MONEDA),
	---CONSTRAINT FK_CLIENTE_CUENTA3 FOREIGN KEY (PAIS_ORIGEN) REFERENCES CLIENTE(PAIS_ORIGEN),
	---CONSTRAINT FK_CLIENTE_CUENTA4 FOREIGN KEY (TIPO_CUENTA) REFERENCES CLIENTE(TIPO_CUENTA)
)
SELECT* FROM CUENTA 

INSERT CUENTA
(ID_CUENTA,TIPO_TRANSACCION,CONTRASEÑA,USUARIO,FECHA_HORA,PAIS_ORIGEN,TIPO_MONEDA,TIPO_CUENTA)--BALANCE,USUARIO,FECHA_HORA)
VALUES
(1,'A','pepitouno','falipondio',GETDATE(),'HUNGRIA','EURO','COMERCIAL')
INSERT CUENTA
(ID_CUENTA,TIPO_TRANSACCION,CONTRASEÑA,USUARIO,FECHA_HORA,PAIS_ORIGEN,TIPO_MONEDA,TIPO_CUENTA)--BALANCE,USUARIO,FECHA_HORA)
VALUES
(2,'A','YOLO','MAMITASPUEBLA',GETDATE(),'MEXICO','DOLAR','PREMIUM')

DROP TABLE CUENTA

--------------------------------------------------------------------------------------------------------------

CREATE TABLE BITCOIN
(
    ID_CUENTA INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    ID_TRANSACCION INT NOT NULL,
    MONTO DECIMAL(6,2) NOT NULL, --6 digitos 2 decimales
    NUM_CLIENTE INT NOT NULL,
    NUM_COMERCIO INT NOT NULL, --(PREGUNTA 7) PAGOS REALIZADOS CON BITCOIN POR COMERICO
    PAIS_ORIGEN VARCHAR(50),--(PREGUNTA 3) EL PAIS QUE MAS SE REPITA ES LA QUE HACE MAYOR TRANSACCIONES CON BITCOIN
    TIPO_CUENTA VARCHAR(50),
    TIPO_MONEDA VARCHAR(50)

    CONSTRAINT PK_NO_TRANSACCION PRIMARY KEY (ID_TRANSACCION),
    CONSTRAINT UC_ID_CUENTAB UNIQUE(ID_CUENTA),
    CONSTRAINT CHK_TIPO_CUENTAB CHECK (TIPO_CUENTA = 'PREMIUM'),
    CONSTRAINT CHK_TIPO_MONEDAB CHECK (TIPO_MONEDA = 'DOLAR'),
    CONSTRAINT CHK_HORA CHECK (HORA>= '08:00:00:000' AND HORA<='14:00:00:000'),
	---CONSTRAINT FK_CUENTA_BITCOIN FOREIGN KEY (TIPO_MONEDA) REFERENCES CUENTA(TIPO_MONEDA),
	---CONSTRAINT FK_CUENTA_BITCOIN2 FOREIGN KEY (PAIS_ORIGEN) REFERENCES CUENTA(PAIS_ORIGEN),
	CONSTRAINT FK_TRANSACCION_BITCOIN3 FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
)

SELECT* FROM BITCOIN ORDER BY CONVERT (DATE, FECHA), CONVERT (TIME, HORA)

INSERT BITCOIN
(ID_CUENTA,FECHA,HORA,ID_TRANSACCION,MONTO,NUM_CLIENTE,NUM_COMERCIO,PAIS_ORIGEN,TIPO_CUENTA,TIPO_MONEDA)
VALUES
(2,GETDATE(),'13:00:00:000',1,'7000','1','1','MEXICO','PREMIUM','DOLAR')

DROP TABLE BITCOIN

--------------------------------------------------------------------------------------------------------------
CREATE TABLE TRANSACCION
(
	ID_TRANSACCION INT NOT NULL,
	FECHAT DATE NOT NULL,
    HORAT TIME NOT NULL,
	NO_COMERCIO INT NOT NULL,
	TIPO_CUENTA VARCHAR(50) NOT NULL,
	MONTO DECIMAL(10,2) NOT NULL,  --10 digitos 2 decimales   --(PREGUNTA 6) MAYORES A 100K O MAS 
	TIPO_TRANSACCION VARCHAR(50) NOT NULL,
	TIPO_MONEDA VARCHAR(50) NOT NULL,
	ID_CUENTA INT NOT NULL,
	NOMBRE_TRANSACCION VARCHAR(50)
	

	CONSTRAINT PK1_ID_TRANSACCAION PRIMARY KEY (ID_TRANSACCION),
	CONSTRAINT CHK1_TIPO_MONEADA CHECK (TIPO_MONEDA = 'DOLAR' OR TIPO_MONEDA = 'EURO'),
	CONSTRAINT UC1_ID_CUENTAA1 UNIQUE(ID_CUENTA),
	CONSTRAINT CHK1_TIPO_CUENTAA CHECK (TIPO_CUENTA = 'COMERCIAL' OR TIPO_CUENTA = 'PREMIUM'),
	CONSTRAINT CHK1_TIPO_TRANSAACCION CHECK (TIPO_TRANSACCION = 'DEPOSITOS' OR TIPO_TRANSACCION = 'RETIROS' OR TIPO_TRANSACCION = 'PCI' OR TIPO_TRANSACCION = 'TCC' OR TIPO_TRANSACCION = 'ICC' OR TIPO_TRANSACCION = 'TCP'),
	CONSTRAINT CHK1_TCOMERCIALEASS CHECK ((TIPO_CUENTA = 'COMERCIAL' AND (TIPO_TRANSACCION = 'DEPOSITOS' OR TIPO_TRANSACCION = 'RETIROS' OR TIPO_TRANSACCION = 'PCI' OR TIPO_TRANSACCION = 'TCC')) OR (TIPO_CUENTA = 'PREMIUM' AND (TIPO_TRANSACCION = 'DEPOSITOS' OR TIPO_TRANSACCION = 'RETIROS' OR TIPO_TRANSACCION = 'TCC' OR TIPO_TRANSACCION = 'ICC' OR TIPO_TRANSACCION = 'TCP'))),
	--PCI = PAGO COMERCIO INTERNACIONAL, TCC = TRANFERENCIAS ENTRE CUENTAS TIPO COMERCIAL, ICC = INVERSIONES A CUENTAS DE CLIENTES, TCP = TRANFERENCIAS ENTRE CUENTAS PREMIUM
	CONSTRAINT FK_CUENTA_TRANSACCION FOREIGN KEY(ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
)
SELECT * FROM TRANSACCION 
WHERE  (HORAT<=('03:00:00:000') OR  HORAT>=('23:00:00:000'))AND  MONTO>=100000
ORDER BY CONVERT (DATE, FECHAT), CONVERT (TIME, HORAT)

INSERT TRANSACCION
(ID_TRANSACCION, FECHAT, HORAT, NO_COMERCIO, TIPO_CUENTA, MONTO, TIPO_TRANSACCION, TIPO_MONEDA, ID_CUENTA, NOMBRE_TRANSACCION)
VALUES
(1, GETDATE(), '23:00:00:000', 1, 'COMERCIAL', 100000.43, 'PCI', 'EURO', 1, 'PAGO COMERCIO 1')



DROP TABLE TRANSACCION
--------------------------------------------------------------------------------------------------------------